### ISSUE TITLE
[RFC] Client Review

### ISSUE THREAD

**Issue by rande** [ekino/php-hal-client#1]
Hello

I am working on a small lib to consume HAL resources. The client must be standalone and allows to navigate and to retrieve automatically related resources.

``` php

$entryPoint = new EntryPoint('http://propilex.herokuapp.com', $client);
$resource = $entryPoint->get(); // return the main resource

$pager = $resource->get('p:documents');

$pager->get('page'); // return the page attribute

$collection = $pager->get('documents'); // return a ResourceCollection

```

There is no http client for now, just the interface used in the unit tests. 

@willdurand @lsmith77 if you have a few minutes it will be great if you can look to the code.

btw, I end up with the same structure as https://github.com/codegram/hyperclient

**Comment by lsmith77** [comment]
Still quite abstract. The only thing that I stumbled over was the ResourceCollection, imho one should pass in the collection as an iterator. Then again one could also offer a factory for this. But an iterator parameter could enable stuff like lazy loading etc.

**Comment by willdurand** [comment]
I love the API.

**Comment by rande** [comment]
@willdurand thanks!

**Comment by hjr3** [comment]
I don't think the client should have a notion of embedded resources. Link rels should be the common abstraction.

I think http://propilex.herokuapp.com provides a misleading example. The `p:documents` link relation should match the embedded `documents` resource. If I ask for documents the client should be making the determination of whether or not to make a HTTP GET request from a link or to use an embedded document. Thoughts?

Also, I have some thoughts about representing collections back. I see tons of servers making this really painful for clients. I will share my thoughts soon!

**Comment by rande** [comment]
closing for now, you can still leave a comment if required
